language: 
  node_js
node_js:
  12.16.3
install: 
  npm install
script: 
  npm test
notifications: 
  email:
    recipients:
      - sunkanjue@163.com
      - other@example.com
    on_success: always # default: change
    on_failure: always # default: always
