language: node_js
node_js: 12.16.3
install: npm install
script: npm run build
notifications:
  email:
    recipients:
    - sunkanjue@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_e6f8047c3a1d_key -iv $encrypted_e6f8047c3a1d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host www.gzxinen.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp -o stricthostkeychecking=no -r build root@www.gzxinen.com:/mnt/git/travis/demo
branches:
  only:
  - develop
